version: "3.9"

services:
  postgres:
    build: .
    container_name: postgres_db
    restart: unless-stopped

    environment:
      POSTGRES_USER: axum
      POSTGRES_PASSWORD: axum123
      POSTGRES_DB: axum_backend

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U axum"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
