max_width = 100
edition = "2021"
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Max"
merge_derives = true

# Code layout (Stable)
struct_lit_width = 80
fn_call_width = 80
chain_width = 80

# Matching (Stable)
match_block_trailing_comma = true
